#!/usr/bin/env node
'use strict'

/**
 * Lifts the crash-test scenarios out of the three runners into a module the
 * comparison page can render side by side.
 *
 * The snippets are generated rather than written by hand on purpose. A hand-kept
 * copy drifts from the code that actually ran the moment anyone edits a runner,
 * and a section whose whole claim is "this is the code you just watched execute"
 * cannot afford to show something else. Regenerating is idempotent: run it twice
 * and the second run leaves the file byte for byte.
 *
 *   node versus/code/gen.cjs
 */

const fs = require( 'fs' )
const path = require( 'path' )

const root = path.join( __dirname, '..', '..' )

/** Where each runner lives and what language its snippet is. */
const sources = [
	{ id: 'react', file: 'assets/versus/react/runner.html', lang: 'js' },
	{ id: 'vue', file: 'assets/versus/vue/runner.html', lang: 'js' },
	{ id: 'mol', file: 'lab/lab.view.ts', lang: 'ts' },
	{ id: 'angular', file: 'assets/versus/angular/runner.html', lang: 'ts' },
	{ id: 'solid', file: 'assets/versus/solid/runner.html', lang: 'js' },
	{ id: 'svelte', file: 'assets/versus/svelte/runner.html', lang: 'js' },
]

const begin = /^\s*\/\/ versus:case (\w+)\s*$/
const end = /^\s*\/\/ versus:end\s*$/

/** Splits one runner into { case: source } by the markers planted in it. */
function regions( text ) {

	const out = {}
	let name = null
	let lines = []

	for( const line of text.split( '\n' ) ) {

		const opened = line.match( begin )

		if( opened || end.test( line ) ) {
			if( name ) out[ name ] = lines
			name = opened ? opened[ 1 ] : null
			lines = []
			continue
		}

		if( name ) lines.push( line )
	}

	if( name ) out[ name ] = lines

	return out
}

/** Strips the shared indentation and the blank lines around the block, so the
 *  snippet reads as its own file rather than as a fragment torn out of one. */
function dedent( lines ) {

	while( lines.length && !lines[ 0 ].trim() ) lines.shift()
	while( lines.length && !lines[ lines.length - 1 ].trim() ) lines.pop()

	const widths = lines
		.filter( line => line.trim() )
		.map( line => ( line.match( /^\t*/ ) || [ '' ] )[ 0 ].length )

	const shift = widths.length ? Math.min( ... widths ) : 0

	return lines.map( line => line.slice( shift ) ).join( '\n' )
}

const collected = {}

for( const source of sources ) {

	const text = fs.readFileSync( path.join( root, source.file ), 'utf8' )
	const found = regions( text )

	// A runner still being written has no markers yet. Skipping it keeps the
	// build moving, but never quietly: a snippet silently missing from the page
	// is the one failure this generator exists to prevent.
	if( !Object.keys( found ).length ) {
		console.warn( `  skipped ${ source.id }: no versus:case markers in ${ source.file }` )
		continue
	}

	for( const [ name, lines ] of Object.entries( found ) ) {
		collected[ name ] = collected[ name ] || {}
		collected[ name ][ source.id ] = {
			lang: source.lang,
			file: source.file,
			text: dedent( lines ),
		}
	}
}

const cases = Object.keys( collected ).sort()

const body = cases.map( name => {
	const per = collected[ name ]
	const inner = Object.keys( per ).sort().map( id => {
		const snippet = per[ id ]
		return `\t\t\t${ id }: {\n`
			+ `\t\t\t\tlang: ${ JSON.stringify( snippet.lang ) },\n`
			+ `\t\t\t\tfile: ${ JSON.stringify( snippet.file ) },\n`
			+ `\t\t\t\ttext: ${ JSON.stringify( snippet.text ) },\n`
			+ `\t\t\t}`
	} ).join( ',\n' )
	return `\t\t${ name }: {\n${ inner }\n\t\t}`
} ).join( ',\n' )

const out = `namespace $ {

	/** One scenario as it is written in one runner. */
	export type $bog_smalljs_versus_code_snippet = {
		readonly lang: string
		readonly file: string
		readonly text: string
	}

	/**
	 * Source of every crash-test scenario, per case and per framework.
	 *
	 * Generated by \`versus/code/gen.cjs\` from the runners themselves — never
	 * edit by hand. The page shows this next to the frames that just ran, so a
	 * snippet that had drifted from the executed code would be worse than no
	 * snippet at all.
	 */
	export const $bog_smalljs_versus_code_data: Readonly< Record< string, Readonly< Record< string, $bog_smalljs_versus_code_snippet > > > > = {
${ body }
	}

}
`

fs.writeFileSync( path.join( __dirname, 'code.ts' ), out )

console.log(
	'generated: code.ts (' + cases.length + ' cases × ' +
	sources.length + ' runners, ' + Math.round( out.length / 1024 ) + ' KB)'
)
