namespace $ {

	/**
	 * Interactive course lessons. GENERATED by content/gen.cjs — edit the lessons
	 * array there and re-run the generator. Code snippets are embedded escaped so
	 * their $mol_* examples are not mistaken for module dependencies.
	 */

	export type $bog_smalljs_lesson = {
		id: string
		title: string
		/** Substring the finished source should contain (simple auto-check). */
		expect: string
		expect_in: 'tree' | 'ts'
		md: string
		start_tree: string
		start_ts: string
		solution_tree: string
		solution_ts: string
	}

	export class $bog_smalljs_lessons extends $mol_object2 {

		static all(): readonly $bog_smalljs_lesson[] {
			return [
				this.lesson( 'hello' )!,
				this.lesson( 'views' )!,
				this.lesson( 'state' )!,
				this.lesson( 'events' )!,
				this.lesson( 'routing' )!,
			]
		}

		static ids(): readonly string[] {
			return [ 'hello', 'views', 'state', 'events', 'routing' ]
		}

		static map(): Readonly< Record< string, $bog_smalljs_lesson > > {
			return {
				'hello': {
					id: 'hello',
					title: "Hello World",
					expect: "Hello",
					expect_in: 'tree',
					md: "# Hello World\n\nWelcome! On the left is a live \u0024mol editor — **view.tree** describes structure and the result renders on the right.\n\nRight now the component shows a placeholder. Change the text after the `\\` and watch the preview update instantly.\n\n**Goal:** make the greeting say hello to \u0024mol.",
					start_tree: "\u0024my_demo \u0024mol_view\n\tsub /\n\t\t<= Greeting \u0024mol_view\n\t\t\tsub / <= greeting \\Edit me\n",
					start_ts: "",
					solution_tree: "\u0024my_demo \u0024mol_view\n\tsub /\n\t\t<= Greeting \u0024mol_view\n\t\t\tsub / <= greeting \\Hello, \u0024mol!\n",
					solution_ts: "",
				},
				'views': {
					id: 'views',
					title: "Views",
					expect: "Subtitle",
					expect_in: 'tree',
					md: "# Views\n\nA view is built from other views. Here `\u0024my_demo` has one child; add a second so the card shows a title *and* a subtitle.\n\n**Goal:** add a `Subtitle` sub-view under `sub /`, with its own text.",
					start_tree: "\u0024my_demo \u0024mol_view\n\tsub /\n\t\t<= Title \u0024mol_view\n\t\t\tsub / <= title \\My component\n",
					start_ts: "",
					solution_tree: "\u0024my_demo \u0024mol_view\n\tsub /\n\t\t<= Title \u0024mol_view\n\t\t\tsub / <= title \\My component\n\t\t<= Subtitle \u0024mol_view\n\t\t\tsub / <= subtitle \\Built from views\n",
					solution_ts: "",
				},
				'state': {
					id: 'state',
					title: "State",
					expect: "\u0024mol_mem",
					expect_in: 'ts',
					md: "# State\n\nLogic lives in **view.ts** — switch to that tab. `@ \u0024mol_mem` makes a value reactive: everything that reads it updates on its own.\n\n**Goal:** in view.ts, give the component a reactive `count()` and a `count_text()` that returns it as a string, so the preview shows a number.\n\nStuck? Press **Solution**.",
					start_tree: "\u0024my_demo \u0024mol_view\n\tcount_text \\?\n\tsub /\n\t\t<= Value \u0024mol_view\n\t\t\tsub / <= count_text\n",
					start_ts: "",
					solution_tree: "\u0024my_demo \u0024mol_view\n\tcount_text \\?\n\tsub /\n\t\t<= Value \u0024mol_view\n\t\t\tsub / <= count_text\n",
					solution_ts: "class \u0024my_demo extends \u0024.\u0024my_demo {\n\t@ \u0024mol_mem count( next?: number ) { return next ?? 5 }\n\tcount_text() { return String( this.count() ) }\n}\n",
				},
				'events': {
					id: 'events',
					title: "Events",
					expect: "\u0024mol_action",
					expect_in: 'ts',
					md: "# Events\n\nInteractivity comes from event handlers. The view.tree already wires the button’s `click` to an `inc?` action — you implement `inc` in view.ts as a `@ \u0024mol_action` that changes state.\n\n**Goal:** make the button increase the count on each click.",
					start_tree: "\u0024my_demo \u0024mol_view\n\tcount_text \\0\n\tinc? null\n\tsub /\n\t\t<= Value \u0024mol_view\n\t\t\tsub / <= count_text\n\t\t<= Button \u0024mol_button_major\n\t\t\tclick? <=> inc?\n\t\t\tsub / <= button_label \\+1\n",
					start_ts: "",
					solution_tree: "\u0024my_demo \u0024mol_view\n\tcount_text \\0\n\tinc? null\n\tsub /\n\t\t<= Value \u0024mol_view\n\t\t\tsub / <= count_text\n\t\t<= Button \u0024mol_button_major\n\t\t\tclick? <=> inc?\n\t\t\tsub / <= button_label \\+1\n",
					solution_ts: "class \u0024my_demo extends \u0024.\u0024my_demo {\n\t@ \u0024mol_mem count( next?: number ) { return next ?? 0 }\n\t@ \u0024mol_action inc() { this.count( this.count() + 1 ) }\n\tcount_text() { return String( this.count() ) }\n}\n",
				},
				'routing': {
					id: 'routing',
					title: "Routing",
					expect: "\u0024mol_state_arg",
					expect_in: 'ts',
					md: "# Routing\n\nThe URL is just reactive state. `\u0024mol_state_arg` reads and writes a query parameter, so a value survives reloads and is shareable.\n\n**Goal:** back the input with a URL argument named `name` in view.ts, and echo it below.",
					start_tree: "\u0024my_demo \u0024mol_view\n\tname? \\\n\techo \\\n\tsub /\n\t\t<= Field \u0024mol_string\n\t\t\tvalue? <=> name?\n\t\t\thint \\Type your name\n\t\t<= Echo \u0024mol_view\n\t\t\tsub / <= echo\n",
					start_ts: "",
					solution_tree: "\u0024my_demo \u0024mol_view\n\tname? \\\n\techo \\\n\tsub /\n\t\t<= Field \u0024mol_string\n\t\t\tvalue? <=> name?\n\t\t\thint \\Type your name\n\t\t<= Echo \u0024mol_view\n\t\t\tsub / <= echo\n",
					solution_ts: "class \u0024my_demo extends \u0024.\u0024my_demo {\n\t@ \u0024mol_mem name( next?: string ) { return \u0024.\u0024mol_state_arg.value( 'name', next ) ?? '' }\n\techo() { return this.name() ? 'Hello, ' + this.name() + '!' : '' }\n}\n",
				},
			}
		}

		static lesson( id: string ): $bog_smalljs_lesson | null {
			return this.map()[ id ] ?? null
		}

		static first(): string { return this.ids()[ 0 ] }

	}

}
