#!/usr/bin/env node
// Build-time semantic index for the docs search.
//
// Runs the all-MiniLM-L6-v2 sentence embedder over every doc page and writes
// the vectors to a static MAM module (embeddings/embeddings.ts) that bundles
// into web.js. The runtime (search.view.ts) embeds the query with the SAME
// model from a CDN and ranks by cosine similarity, merged with full-text.
//
// This is NOT part of gen.cjs / the pre-commit hook — it needs @xenova/
// transformers (a heavy, network-fetching dev dep) and only has to re-run when
// the docs change enough to matter. Run manually:
//
//   npm install --no-save @xenova/transformers
//   node content/embed.cjs
//
// One-shot process: the model loads once and node exits when done, so there is
// no long-lived leak.

const fs = require( 'fs' )
const path = require( 'path' )

const root = __dirname
const docs_dir = path.join( root, 'en', 'docs' )
const out_dir = path.join( root, '..', 'embeddings' )
const MODEL = 'Xenova/all-MiniLM-L6-v2'

// Strip markdown to plain-ish text so the embedding sees content, not syntax.
function clean( md ) {
	return md
		.replace( /```[\s\S]*?```/g, ' ' )
		.replace( /`([^`]*)`/g, '$1' )
		.replace( /\[([^\]]*)\]\([^)]*\)/g, '$1' )
		.replace( /[#>*_|-]/g, ' ' )
		.replace( /\s+/g, ' ' )
		.trim()
}

async function main() {
	const { pipeline } = await import( '@xenova/transformers' )
	const extract = await pipeline( 'feature-extraction', MODEL )

	const files = fs.readdirSync( docs_dir ).filter( f => f.endsWith( '.md' ) ).sort()
	const index = []

	for ( const file of files ) {
		const slug = file.replace( /\.md$/, '' )
		const md = fs.readFileSync( path.join( docs_dir, file ), 'utf8' )
		const title = ( md.match( /^#\s+(.+)$/m ) || [] )[ 1 ] || slug
		// Title carries the topic; prepend it, then cap length (model truncates
		// to 256 tokens anyway — a slice keeps memory and time small).
		const text = ( title + '. ' + clean( md ) ).slice( 0, 2000 )

		const out = await extract( text, { pooling: 'mean', normalize: true } )
		const vector = Array.from( out.data ).map( x => Math.round( x * 1e4 ) / 1e4 )
		if ( typeof out.dispose === 'function' ) out.dispose()

		index.push( { slug, vector } )
		process.stdout.write( `  embedded ${ slug } (${ vector.length }d)\n` )
	}

	const dim = index[ 0 ] ? index[ 0 ].vector.length : 384
	const rows = index.map( r =>
		`\t\t\t\t{ slug: '${ r.slug }', vector: [ ${ r.vector.join( ', ' ) } ] },`
	).join( '\n' )

	const ts = `namespace $ {

	/**
	 * Static semantic index for docs search. GENERATED by content/embed.cjs —
	 * do not edit by hand. Vectors are ${ dim }-dim, produced by ${ MODEL }
	 * (mean-pooled, L2-normalized). The runtime embeds the query with the same
	 * model and ranks by cosine similarity. Re-run: node content/embed.cjs
	 */
	export type $bog_smalljs_embeddings_row = {
		slug: string
		vector: readonly number[]
	}

	export class $bog_smalljs_embeddings extends $mol_object2 {

		static model(): string { return '${ MODEL }' }
		static dim(): number { return ${ dim } }

		static index(): readonly $bog_smalljs_embeddings_row[] {
			return [
${ rows }
			]
		}

	}

}
`

	fs.mkdirSync( out_dir, { recursive: true } )
	fs.writeFileSync( path.join( out_dir, 'embeddings.ts' ), ts )
	console.log( `generated: embeddings/embeddings.ts (${ index.length } pages, ${ dim }d)` )
}

main().catch( err => { console.error( err ); process.exit( 1 ) } )
