#!/usr/bin/env node
// Generates content.ts from the .md sources in content/en/docs/.
//
// Why a generator: MAM's TS dependor (mol/build/build.node.ts) scans the whole
// source text for `$name` and `require(...)`/`import(...)` tokens and treats
// them as module deps. Example code embedded in docs (e.g. `$my_hello`,
// `require('moment')`) would become broken deps and fail the audit. So we embed
// each page as a JS string with `$` written `$` and `require(`/`import(`
// neutralized — invisible to the dependor, exact same text at runtime.
//
// Re-run after editing any .md or the manifest below:  node content/gen.cjs

const fs = require( 'fs' )
const path = require( 'path' )

const root = __dirname
const docs_dir = path.join( root, 'en', 'docs' )

// --- Manifest: sidebar order/groups + page metadata. Single source of layout.
const sections = [
	{
		id: 'docs',
		title: 'Docs',
		groups: [
			{ title: 'Getting Started', pages: [ 'introduction', 'getting-started' ] },
			{ title: 'Essentials', pages: [ 'installation', 'views', 'state', 'routing', 'rendering' ] },
			{ title: 'Data', pages: [ 'data', 'giper-baza' ] },
		],
	},
]

// title + one-line summary (summary feeds llms.txt).
const meta = {
	'introduction': { title: 'Introduction', summary: 'What $mol is, who it is for, and a taste of reactive views.' },
	'getting-started': { title: 'Getting Started', summary: 'From an empty folder to a running, reactive $mol app in under 15 minutes.' },
	'installation': { title: 'Installation', summary: 'The MAM workspace, module layout, dev server, and production build.' },
	'views': { title: 'Views', summary: 'Declaring and composing components with the view.tree language.' },
	'state': { title: 'State & Reactivity', summary: 'Reactive properties, actions vs. computations, keyed and async state.' },
	'routing': { title: 'Routing', summary: 'The URL as reactive state: screens, links, and multiple parameters.' },
	'rendering': { title: 'Rendering', summary: 'No virtual DOM, lazy components, and virtualized rendering — plus reproducible benchmarks.' },
	'data': { title: 'Data Fetching', summary: 'Loading remote data with reactive async properties and loading states.' },
	'giper-baza': { title: 'Giper Baza', summary: 'Local-first data with automatic sync: entities, atoms, and CRUD.' },
}
const titles = Object.fromEntries( Object.entries( meta ).map( ( [ k, v ] ) => [ k, v.title ] ) )

const default_slug = 'introduction'

// Production base where the deploy step copies the raw .md endpoints + llms.txt.
const prod_base = 'https://b-on-g.github.io/smalljs'

// --- Embed a raw string so MAM's dependor never mistakes example code for deps.
function embed( text ) {
	return JSON.stringify( text )
		.replace( /\$/g, '\\u0024' )
		.replace( /\brequire\(/g, 'require\\u0028' )
		.replace( /\bimport\(/g, 'import\\u0028' )
}

const slugs = Object.keys( titles )

const page_entries = slugs.map( slug => {
	const file = `content/en/docs/${ slug }.md`
	const md = fs.readFileSync( path.join( docs_dir, `${ slug }.md` ), 'utf8' )
	return (
		`\t\t\t\t'${ slug }': {\n` +
		`\t\t\t\t\tslug: '${ slug }',\n` +
		`\t\t\t\t\ttitle: ${ JSON.stringify( titles[ slug ] ) },\n` +
		`\t\t\t\t\tfile: '${ file }',\n` +
		`\t\t\t\t\tmd: ${ embed( md ) },\n` +
		`\t\t\t\t},`
	)
} ).join( '\n' )

const out = `namespace $ {

	/**
	 * Docs content registry for smalljs. GENERATED by content/gen.cjs — do not
	 * edit by hand; edit the .md sources in content/en/docs/ and re-run the
	 * generator. Markdown is embedded (not fetched) so it bundles into web.js
	 * and works with the app/- deploy and the prerender step.
	 */

	export type $bog_smalljs_content_page = {
		slug: string
		title: string
		/** GitHub-relative path, for the Edit-on-GitHub link. */
		file: string
		md: string
	}

	export type $bog_smalljs_content_group = {
		title: string
		pages: readonly string[]
	}

	export type $bog_smalljs_content_section = {
		id: string
		title: string
		groups: readonly $bog_smalljs_content_group[]
	}

	export class $bog_smalljs_content extends $mol_object2 {

		static sections(): readonly $bog_smalljs_content_section[] {
			return ${ JSON.stringify( sections, null, '\t' ).replace( /\n/g, '\n\t\t\t' ) }
		}

		static pages(): Readonly< Record< string, $bog_smalljs_content_page > > {
			return {
${ page_entries }
			}
		}

		/** Flat ordered slug list for prev/next. */
		static order( section = 'docs' ): readonly string[] {
			const sec = this.sections().find( s => s.id === section )
			if ( !sec ) return []
			return sec.groups.flatMap( g => g.pages )
		}

		static page( slug: string ): $bog_smalljs_content_page | null {
			return this.pages()[ slug ] ?? null
		}

		static default_slug(): string {
			return '${ default_slug }'
		}

	}

}
`

fs.writeFileSync( path.join( root, 'content.ts' ), out )

// --- llms.txt (llmstxt.org) so Claude/Cursor can cite the docs. --------------
let llms = `# smalljs\n\n`
llms += `> Documentation for $mol — a reactive UI framework with typed views, automatic reactivity, and no virtual DOM. Each page below is available as raw Markdown at the linked URL.\n\n`
for ( const sec of sections ) {
	for ( const group of sec.groups ) {
		llms += `## ${ group.title }\n\n`
		for ( const slug of group.pages ) {
			llms += `- [${ meta[ slug ].title }](${ prod_base }/docs/${ slug }.md): ${ meta[ slug ].summary }\n`
		}
		llms += `\n`
	}
}
fs.writeFileSync( path.join( root, 'llms.txt' ), llms )

console.log( `generated: content.ts (${ slugs.length } pages) + llms.txt` )
